// generated by stringer -type=AddrMode; DO NOT EDIT

package instr

import "fmt"

const _AddrMode_name = "ModeNoneMode2Reg3Mode2Reg4Mode2Reg5ModeBranchModeDesModeElpmLpmEnhancedModeInModeIOBitModeLdModeLddModeLdsModeLds16ModeOutModePcModePcOffModeReg5ModeRegBitModeRegImmModeRegPairModePairImmModeSBitModeStModeStdModeStsModeSts16ModeSpmXmega"

var _AddrMode_index = [...]uint8{0, 8, 17, 26, 35, 45, 52, 71, 77, 86, 92, 99, 106, 115, 122, 128, 137, 145, 155, 165, 176, 187, 195, 201, 208, 215, 224, 236}

// String returns the string representation of an AddrMode. For
// example,
//  Mode2Reg5.String() == "Mode2Reg5"
func (i AddrMode) String() string {
	if i < 0 || i+1 >= AddrMode(len(_AddrMode_index)) {
		return fmt.Sprintf("AddrMode(%d)", i)
	}
	return _AddrMode_name[_AddrMode_index[i]:_AddrMode_index[i+1]]
}
