// generated by stringer -type=Mode; DO NOT EDIT

package instr

import "fmt"

const _Mode_name = "ModeA5B3ModeA6D5ModeB3ModeB3K7ModeB3D5ModeD3R3ModeD4K8ModeD4R4ModeD5ModeD5K16ModeD5R5ModeDDDDRRRRModeDDK6ModeElpmModeK4ModeK12ModeK22ModeLddStdModeLdStModeLpmModeNoneModeSpm"

var _Mode_index = [...]uint8{0, 8, 16, 22, 30, 38, 46, 54, 62, 68, 77, 85, 97, 105, 113, 119, 126, 133, 143, 151, 158, 166, 173}

func (i Mode) String() string {
	if i < 0 || i+1 >= Mode(len(_Mode_index)) {
		return fmt.Sprintf("Mode(%d)", i)
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
